### ISSUE TITLE
minor mistake in the article about multiple dispatch

### ISSUE THREAD

**Issue by qwerty123456asdfgh** [miguelraz/miguelraz.github.io#1]
Hi, I was reading the article about multiple dispatch and found a minor addition mistake, i think someone might find it interesting.
Oh, and thanks for the content !

![Capture](https://user-images.githubusercontent.com/88000365/137371706-43935797-9770-450c-a210-d9f12a62db61.PNG)

**Comment by miguelraz** [comment]
Jeebus... well that was humbling.
Thanks for the fix @Galacspace , and if you wanna see more content, don't forget you can sponsor me :D

**Comment by miguelraz** [comment]
Pushed and fixed in [next commit](https://github.com/miguelraz/miguelraz.github.io/commit/a38f0c6c856160960a2da45fa25f4575fa141b53).
