### ISSUE TITLE
literal juxtaposition wat

### ISSUE THREAD

**Issue by StefanKarpinski** [miguelraz/miguelraz.github.io#2]
Here's an example inspired by a wat posted on Slack, now lost in the Slackhole:
```jl
julia> e = 9998.0
9998.0

julia> 2e
19996.0

julia> 2e+4
20000.0

julia> 2e+5
```
What is the last output? Is it `20001.0`? It is not.

**Comment by miguelraz** [comment]
marvelously cursed, thank you, will add.

**Comment by miguelraz** [comment]
submitted on latest commit.

**Comment by StefanKarpinski** [comment]
Might want to include the actual value at the end.

**Comment by miguelraz** [comment]
Ah, missed that last bit - pushed fix on master.

**Comment by pnrao** [comment]
Reproducible with `f` also,

```julia
julia> f=9998.0
9998.0

julia> 2f
19996.0

julia> 2f+4
20000.0f0

julia> 2f+5
200000.0f0

julia> 2f+6
2.0f6
```

The `f+` forces interpretation as Float32 literals.

**Comment by jonas-schulze** [comment]
> Reproducible with `f` also,

ref https://github.com/JuliaLang/julia/issues/43469
